[project]
name = "kunshort-django-wallet"
version = "1.1.1"
description = "Django wallet module with wallet models and services"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.3",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]

[tool.setuptools.packages.find]
include = ["wallets*"]
exclude = ["wallets.tests*"]
