# Generated by Django 6.0.3 on 2026-05-09 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0015_widen_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactionStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='external_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifier supplied by the external system that drove this transaction.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='walletactivities',
            name='action_type',
            field=models.CharField(choices=[('wallet_created', 'Wallet created'), ('top_up', 'Top up'), ('withdrawal', 'Withdrawal'), ('beneficiary_added', 'Beneficiary added'), ('beneficiary_removed', 'Beneficiary removed'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('spending_limit_set', 'Spending limit set'), ('spending_limit_updated', 'Spending limit updated'), ('balance_visibility_changed', 'Balance visibility changed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='walletbeneficiaryactivity',
            name='action_type',
            field=models.CharField(choices=[('added', 'Beneficiary added'), ('removed', 'Beneficiary removed'), ('transfer_out', 'Transfer out'), ('spending_limit_set', 'Spending limit set'), ('spending_limit_updated', 'Spending limit updated'), ('balance_visibility_changed', 'Balance visibility changed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_transaction_id__isnull', False)), fields=('external_transaction_id',), name='wallet_transaction_unique_external_id'),
        ),
        migrations.AddField(
            model_name='wallettransactionstatus',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='wallets.wallettransaction'),
        ),
    ]
