# Generated by Django 6.0.3 on 2026-05-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0016_wallettransactionstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbeneficiaryactivity',
            name='action_type',
            field=models.CharField(choices=[('added', 'Beneficiary added'), ('removed', 'Beneficiary removed'), ('withdrawal', 'Withdrawal'), ('transfer_out', 'Transfer out'), ('spending_limit_set', 'Spending limit set'), ('spending_limit_updated', 'Spending limit updated'), ('balance_visibility_changed', 'Balance visibility changed')], max_length=30),
        ),
    ]
